### ISSUE TITLE
Dois tipo de retorno na rota counties

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-api#54]
A rota `[GET] counties/id` está retornando coisas diferentes dependendo do id que é passado. No banco deve ter municípios de dois formatos. Verificar isso e retornar apenas um formato, de forma consistente, excluindo o formato antigo do banco.

**Comment by carloszan** [comment]
O schema que está atualmente é:

```
@Schema({ versionKey: false })
export class County extends AbstractDocument {
  @Prop()
  name: string;

  @Prop({ type: Info })
  info?: Info;

  @Prop({ type: Contact })
  contact?: Contact;

  @Prop()
  county_id?: Types.ObjectId;
}
```

Podemos ver que info, contact e county_id são opcionais.

**Comment by DaniGomes** [comment]
Acredito que podemos fechar essa. Foi verificado que os dados retornados estão consistentes.
