### ISSUE TITLE
Habilitar edição e exclusão de demanda

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-api#62]

**Comment by carloszan** [comment]
As rotas que existem agora nao estao funcionando? 

- (PATCH) /demands/:id
- (DELETE) /demands/:id

**Comment by carloszan** [comment]
Aparentemente o PATCH nao está funcionando e o DELETE está.

**Comment by DaniGomes** [comment]
Não vamos disponibilizar edição de demanda agora e a exclusão está funcionando, então vou fechar essa issue.
