### ISSUE TITLE
Atualizar roles na API

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-api#65]
Essa é a correspondência que temos no frontend hoje:

`export enum Role {
  Admin = "admin",
  Cisab = "cisab",
  Townhall = "townhall",
  Autarky = "autarky",
  Employee = "employee",
}
`

**Comment by carloszan** [comment]
Temos um Role Manager que gerencia o Townhall e Autarky. Como fazemos com esse caso?

**Comment by DaniGomes** [comment]
Não precisamos separadamente de um perfil para o gerente e para a instituição. O que eles teriam de diferente?
A meu ver, quem tiver o perfil da instituição é quem gerencia ela. Para ficar mais claro, pode chamar de TownhallManager e AutarkyManager, se for o caso.

**Comment by carloszan** [comment]
Foi decidido apenas alterar o County para Employee
