### ISSUE TITLE
Rota de recuperar todos os produtos tem que ser liberada para os usuários

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-api#68]
Ao fazer uma requisição para a rota de recuperar a lista de produtos pelo perfil da Cisab, o retorno está correto. Mas ao fazer a mesma operação com outro usuário, o retorno é 403 Forbidden. Mas os usuários precisam acessar essa rota para conseguirem sugerir novos produtos. Já que na tela de criação de um produto, é necessário mostrar a lista de produtos que podem ser acessórios de outros.

**Comment by carloszan** [comment]
Essa rota deve ser visualizada pela Cisab, Townhall, Autarky e Employee?

O codigo está [aqui](https://github.com/poliedros/cisab-api/blob/main/src/products/products.controller.ts#L54).

**Comment by DaniGomes** [comment]
Sim, o `@Get() findAll` todos esses tem que poder acessar. 
Já o `@Patch(':id')  update(` só a CIsab pode, já que só ela atualiza produtos.
