### ISSUE TITLE
Rota de criação de usuários tem que ser liberada para instiuições

### ISSUE THREAD

**Issue by DaniGomes** [poliedros/cisab-api#69]
A rota `/counties/${req.query.id}/users` está retornando 403 quando uma prefeitura ou autarquia está logada. Dessa forma, elas não estão conseguindo criar seus funcionários.

**Comment by carloszan** [comment]
Realmente, o codigo [esta como](https://github.com/poliedros/cisab-api/blob/main/src/counties/counties.controller.ts#L106):
`
  @Roles(Role.Cisab)
`

Esse endpoint poderá ser usado pelas roles Townhall e Autarky?

`
  @Roles(Role.Cisab, Role.Autarky, Role.Townhall)
`

**Comment by DaniGomes** [comment]
Isso, liberar para esses três que você citou.

**Comment by carloszan** [comment]
Como foi alterado na issue #65, optamos por continuar com a role Manager sem precisar separar Autarky de Townhall.
